Get http://localhost:3001/api/persons/

###


 POST http://localhost:3001/api/persons/
Content-Type:  application/json

{
    "name":"Jinnen",
    "number":"77771111"
}

DELETE  http://localhost:3001/api/persons/

Content-Type:  application/json

{
    "name":"Jinneon",
    "number":"7777aa21111",
    "id":"625fb0bca901325ee7b3c8"
}
.